"""add_context_id_to_personas

Revision ID: 38d373eddc41
Revises: ce143f87c388
Create Date: 2026-03-14 23:44:38.835990
"""
from alembic import op
import sqlalchemy as sa


revision: str = '38d373eddc41'
down_revision = 'ce143f87c388'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personas', sa.Column('context_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'personas', 'contexts', ['context_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'personas', type_='foreignkey')
    op.drop_column('personas', 'context_id')
    # ### end Alembic commands ###
