"""add_contexts_table

Revision ID: ce143f87c388
Revises: 66fdc93ca7a1
Create Date: 2026-03-14 23:33:31.320363
"""
from alembic import op
import sqlalchemy as sa


revision: str = 'ce143f87c388'
down_revision = '66fdc93ca7a1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contexts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contexts')
    # ### end Alembic commands ###
