"""add_cognito_sub_to_users

Revision ID: fa0610656cbc
Revises: 38d373eddc41
Create Date: 2026-03-17 21:56:54.551388
"""
from alembic import op
import sqlalchemy as sa


revision: str = 'fa0610656cbc'
down_revision = '38d373eddc41'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('personas', 'context_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('users', sa.Column('cognito_sub', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'users', ['cognito_sub'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'cognito_sub')
    op.alter_column('personas', 'context_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
